### ISSUE TITLE
Can't run LtrDetector

### ISSUE THREAD

**Issue by JulieDaz** [TulsaBioinformaticsToolsmith/LtrDetector#3]
Hello,

So I downloaded LtrDetector today and tried to run it. The _make_ raises 1 error and some warnings (please see them at the bottom of the message).

Then if I ran in my LtrDetector folder LtrDetector -help, it says command not found. And I can't find the file anywhere

I'm running on MacOS, and I uncommented the MacOS lines in the make file and commented the Linux ones.

Also, by looking at the other issues, I saw something about a start.py script. Is it obsolete now? because I can't find it.

Thanks for your help!

> jd493@ls019981:~/Downloads/LtrDetector-master/src$
> 
>  make tr -j
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c test/TestTr.cpp -o ../bin/TestTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c exception/InvalidInputException.cpp -o ../bin/exception/InvalidInputException.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c exception/FileDoesNotExistException.cpp -o ../bin/exception/FileDoesNotExistException.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c exception/InvalidStateException.cpp -o ../bin/exception/InvalidStateException.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c exception/InvalidOperationException.cpp -o ../bin/exception/InvalidOperationException.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/Tr.cpp -o ../bin/tr/Tr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/BackwardTr.cpp -o ../bin/tr/BackwardTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/ForwardTr.cpp -o ../bin/tr/ForwardTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/Candidate.cpp -o ../bin/tr/Candidate.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/PairContainer.cpp -o ../bin/tr/PairContainer.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/ScorerTr.cpp -o ../bin/tr/ScorerTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c nonltr/Chromosome.cpp -o ../bin/nonltr/Chromosome.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c nonltr/ChromosomeOneDigit.cpp	-o ../bin/nonltr/ChromosomeOneDigit.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c nonltr/ChromosomeRandom.cpp -o ../bin/nonltr/ChromosomeRandom.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/TrKVisitor.cpp -o ../bin/tr/TrKVisitor.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/TrCsVisitor.cpp -o ../bin/tr/TrCSVisitor.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/TrSineVisitor.cpp -o ../bin/tr/TrSineVisitor.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/FilterTr.cpp -o ../bin/tr/FilterTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/LtrTe.cpp -o ../bin/tr/LtrTe.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/DetectorTr.cpp -o ../bin/tr/DetectorTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/MatchTr.cpp -o ../bin/tr/MatchTr.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/Util.cpp -o ../bin/utility/Util.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/Location.cpp -o ../bin/utility/Location.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/EmptyLocation.cpp -o ../bin/utility/EmptyLocation.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/LCS.cpp -o ../bin/utility/LCS.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/LCSLen.cpp -o ../bin/utility/LCSLen.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/LCSubStr.cpp -o ../bin/utility/LCSubStr.o
> clang: clang: warning: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]-lomp: 'linker' input unused [-Wunused-command-line-argument]
> 
> clangclang: warning: : -lomp: 'linker' input unused [-Wunused-command-line-argument]
> warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/TSD.cpp -o ../bin/utility/TSD.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/EmptyTSD.cpp -o ../bin/utility/EmptyTSD.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/TailFinder.cpp -o ../bin/utility/TailFinder.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/Tail.cpp -o ../bin/utility/Tail.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]clang
> : warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/EmptyTail.cpp -o ../bin/utility/EmptyTail.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c tr/TrCollector.cpp -o ../bin/tr/TrCollector.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/GlobAlignE.cpp -o ../bin/utility/GlobAlignE.o
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c utility/LocAlign.cpp -o ../bin/utility/LocAlign.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> /usr/bin/g++   -Xpreprocessor -fopenmp -lomp  -std=c++11 -g -O3 -fmessage-length=0  -c nonltr/ChromListMaker.cpp -o ../bin/nonltr/ChromListMaker.o
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clangclang: : warningwarning: : -lomp: 'linker' input unused [-Wunused-command-line-argument]-lomp: 'linker' input unused [-Wunused-command-line-argument]
> 
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
> In file included from In file included from tr/PairContainer.cpp:1:
> In file included from tr/PairContainer.h:3:
> tr/Candidate.cpp:1:
> tr/Candidate.h:3:17: warning: using directive refers to implicitly-defined namespace 'std'
> tr/Candidate.h:3:17:using namespace std;
>                 ^
> warning: using directive refers to implicitly-defined namespace 'std'
> using namespace std;
>                 ^
> tr/TrCsVisitor.cpp:63:3: warning: '/*' within block comment [-Wcomment]
>                 /*
>                 ^
> tr/LtrTe.cpp:65:2: warning: delete called on 'utility::ITSD' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>         delete shiftedTSD;
>         ^
> tr/LtrTe.cpp:69:2: warning: delete called on 'utility::ITail' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>         delete shiftedTail;
>         ^
> tr/LtrTe.cpp:110:3: warning: delete called on 'utility::ITSD' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>                 delete tsd;
>                 ^
> tr/LtrTe.cpp:114:3: warning: delete called on 'utility::ITail' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>                 delete ppt;
>                 ^
> utility/TSD.cpp:146:3: warning: delete called on 'utility::ILocation' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>                 delete ltTsd;
>                 ^
> utility/TSD.cpp:150:3: warning: delete called on 'utility::ILocation' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>                 delete rtTsd;
>                 ^
> utility/TailFinder.cpp:293:7: warning: expression result unused [-Wunused-value]
>                 for(x; x >searchStart;x--){
>                     ^
> utility/TailFinder.cpp:441:7: warning: expression result unused [-Wunused-value]
>                 for(x; x >searchStart;x--){
>                     ^
> In file included from utility/LCSubStr.cpp:9:
> utility/Util.h:67:4: warning: delete called on 'utility::ILocation' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
>                         delete deleteMe->back();
>                         ^
> utility/LCSubStr.cpp:69:8: note: in instantiation of function template specialization 'utility::Util::deleteInVector<utility::ILocation>' requested here
>         Util::deleteInVector(subStr1);
>               ^
> tr/FilterTr.cpp:152:22: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
>                 else if(smallerLen = downLen){
>                         ~~~~~~~~~~~^~~~~~~~~
> tr/FilterTr.cpp:152:22: note: place parentheses around the assignment to silence this warning
>                 else if(smallerLen = downLen){
>                                    ^
>                         (                   )
> tr/FilterTr.cpp:152:22: note: use '==' to turn this assignment into an equality comparison
>                 else if(smallerLen = downLen){
>                                    ^
>                                    ==
> 1 warning generated.
> 1 warning generated.
> test/TestTr.cpp:32:10: fatal error: 'experimental/filesystem' file not found
> #include <experimental/filesystem>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~
> tr/TrCollector.cpp:372:44: warning: '/*' within block comment [-Wcomment]
>         outMask.open(outputFile.c_str(), ios::out /*| ios::app);
>                                                   ^
> 1 error generated.
> make: *** [../bin/TestTr.o] Error 1
> make: *** Waiting for unfinished jobs....
> 2 warnings generated.
> 4 warnings generated.
> 1 warning generated.
> 1 warning generated.
> 2 warnings generated.
> 1 warning generated.
> 1 warning generated.

**Comment by josephvalencia** [comment]
Hello Julie.

The issue was that the default clang compiler on MacOS does not natively support openMP (which caused the warnings) or <experimental/filesystem> (which caused the error). I just pushed a new Readme and Makefile that supplant the old instructions by requiring you to install the newest version of the gcc compiler.

start.py has been replaced with the command:
``` make bin```

Thanks

Joseph

**Comment by JulieDaz** [comment]
Hi Joseph,

Thank you for your quick answer. I cloned the newest version on my laptop, and followed the new information, but I still get an error.

I looked online the whole morning but can't find anything related...

Thanks

> jd493@ls019981:~/Downloads/LtrDetector-master/src$ make tr -j
> /usr/local/Cellar/gcc/8.3.0/bin/g++-8 -Xpreprocessor -fopenmp -lomp -std=c++17 -g -O3 -fmessage-length=0  -o ../bin/LtrDetector ../bin/TestTr.o ../bin/exception/InvalidInputException.o ../bin/exception/FileDoesNotExistException.o ../bin/exception/InvalidStateException.o ../bin/exception/InvalidOperationException.o ../bin/tr/Tr.o ../bin/tr/BackwardTr.o ../bin/tr/ForwardTr.o ../bin/tr/Candidate.o ../bin/tr/PairContainer.o ../bin/tr/ScorerTr.o ../bin/nonltr/Chromosome.o ../bin/nonltr/ChromosomeOneDigit.o ../bin/nonltr/ChromosomeRandom.o ../bin/tr/TrKVisitor.o ../bin/tr/TrCSVisitor.o ../bin/tr/TrSineVisitor.o ../bin/tr/FilterTr.o ../bin/tr/LtrTe.o ../bin/tr/DetectorTr.o ../bin/tr/MatchTr.o ../bin/utility/Util.o ../bin/utility/Location.o ../bin/utility/EmptyLocation.o ../bin/utility/LCS.o ../bin/utility/LCSLen.o ../bin/utility/LCSubStr.o ../bin/utility/TSD.o ../bin/utility/EmptyTSD.o ../bin/utility/TailFinder.o ../bin/utility/Tail.o ../bin/utility/EmptyTail.o ../bin/tr/TrCollector.o ../bin/utility/GlobAlignE.o ../bin/utility/LocAlign.o ../bin/nonltr/ChromListMaker.o -lstdc++fs
> ld: library not found for -lomp
> collect2: error: ld returned 1 exit status
> make: *** [../bin/LtrDetector] Error 1

**Comment by josephvalencia** [comment]
It looks like you are still using the old Makefile somehow. The flags -Xpreprocessor -fopenmp -lomp should no longer be active as they are commented  out on the Makefile. We simplified the instructions so that they are the same on Mac and OS so there is no need to uncomment the line with these flags.

In other words, verify that the top two lines of your Makefile are:

CXX= g++-8

CXXFLAGS = -std=c++11 -g -O3 -fopenmp -fmessage-length=0

**Comment by JulieDaz** [comment]
Hi,

Oh ok sorry, I thought I still needed to change it. Now the installation is working thanks! 

But now in the bin folder, if I run LtrDetector -help, it says 

> LtrDetector: command not found

What's wrong?

**Comment by josephvalencia** [comment]
Assuming you have not added the bin directory to your PATH, you will need to run it as ./LtrDetector -help.

**Comment by JulieDaz** [comment]
Indeed! Stupid mistake, I didn't think about that... Thank you so much for your quick help!
